### ISSUE TITLE
Connecting to ssb js server

### ISSUE THREAD

**Issue by arj03** [Kuska-ssb/kuska-ssb#8]
Hi @adria0

I was trying to this out to see how it works and got it to compile but after trying to connect to my pub it dies after the initial handshake. Is it supposed to work again a js implementation? 

```
./target/debug/examples/ssb-cli -c between-two-worlds.dk:8008:lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=
```

**Comment by adria0** [comment]
Hi @arj03, what is the error message? Can you try to run it again with tracing enabled?

`RUST_LOG=debug RUST_BACKTRACE=1 ./target/debug/examples/ssb-cli -c between-two-worlds.dk:8008:lbocEWqF2Fg6WMYLgmfYvqJlMfL7hiqVAV6ANjHWNw8=`

**Comment by arj03** [comment]
If I do that I get:

```
thread 'main' panicked at 'internal error: entered unreachable code', examples/ssb-cli.rs:93:22
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
             at /usr/src/rustc-1.41.0/src/libstd/panicking.rs:404
   7: ssb_cli::get_async::{{closure}}
             at examples/ssb-cli.rs:93
   8: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /usr/src/rustc-1.41.0/src/libstd/future.rs:43
   9: std::future::poll_with_tls_context
             at /usr/src/rustc-1.41.0/src/libstd/future.rs:99
  10: ssb_cli::main::main::{{closure}}
             at examples/ssb-cli.rs:194
  11: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /usr/src/rustc-1.41.0/src/libstd/future.rs:43
  12: std::future::poll_with_tls_context
             at /usr/src/rustc-1.41.0/src/libstd/future.rs:99
  13: ssb_cli::main::{{closure}}
             at examples/ssb-cli.rs:132
  14: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /usr/src/rustc-1.41.0/src/libstd/future.rs:43
  15: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/builder.rs:174
  16: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/task_locals_wrapper.rs:60
  17: std::thread::local::LocalKey<T>::try_with
             at /usr/src/rustc-1.41.0/src/libstd/thread/local.rs:262
  18: std::thread::local::LocalKey<T>::with
             at /usr/src/rustc-1.41.0/src/libstd/thread/local.rs:239
  19: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/task_locals_wrapper.rs:55
  20: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/builder.rs:172
  21: smol::run::run::{{closure}}::{{closure}}
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/run.rs:144
  22: scoped_tls_hkt::ScopedKey<T>::set
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:488
  23: smol::throttle::setup
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/throttle.rs:31
  24: smol::run::run::{{closure}}
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/run.rs:144
  25: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.41.0/src/libcore/ops/function.rs:232
  26: smol::context::enter
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/context.rs:8
  27: smol::run::run::{{closure}}::{{closure}}
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/run.rs:112
  28: scoped_tls_hkt::ScopedKey<T>::set
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-hkt-0.1.2/src/lib.rs:488
  29: smol::thread_local::ThreadLocalExecutor::enter
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/thread_local.rs:57
  30: smol::run::run::{{closure}}
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/run.rs:112
  31: smol::run::run::{{closure}}::{{closure}}
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/run.rs:113
  32: smol::work_stealing::WORKER::<impl smol::work_stealing::WORKER>::set
             at ./<::scoped_tls_hkt::scoped_thread_local macros>:40
  33: smol::work_stealing::Worker::enter
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/work_stealing.rs:149
  34: smol::run::run::{{closure}}
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/run.rs:113
  35: smol::run::run
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/smol-0.1.11/src/run.rs:115
  36: async_std::task::builder::Builder::blocking::{{closure}}
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/builder.rs:154
  37: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/task_locals_wrapper.rs:60
  38: std::thread::local::LocalKey<T>::try_with
             at /usr/src/rustc-1.41.0/src/libstd/thread/local.rs:262
  39: std::thread::local::LocalKey<T>::with
             at /usr/src/rustc-1.41.0/src/libstd/thread/local.rs:239
  40: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/task_locals_wrapper.rs:55
  41: async_std::task::builder::Builder::blocking
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/builder.rs:154
  42: async_std::task::block_on::block_on
             at /home/arj/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.0/src/task/block_on.rs:33
  43: ssb_cli::main
             at examples/ssb-cli.rs:132
  44: std::rt::lang_start::{{closure}}
             at /usr/src/rustc-1.41.0/src/libstd/rt.rs:67
  45: std::panicking::try::do_call
  46: __rust_maybe_catch_panic
  47: std::rt::lang_start_internal
  48: std::rt::lang_start
             at /usr/src/rustc-1.41.0/src/libstd/rt.rs:67
  49: main
  50: __libc_start_main
  51: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by adria0** [comment]
Fixed in https://github.com/Kuska-ssb/ssb/commit/96573e402376a1fda37a38cccc9e19ccbacb91ac, should work!

**Comment by arj03** [comment]
That works, thanks! Using this I was able to replicate my feed using the cli. 

I was looking over the source yesterday, impressive work. And not that many lines of code. I havn't done any rust but from old c++ background I see can quite a lot of the same patterns.
